### ISSUE TITLE
Strange strip on the left of document

### ISSUE THREAD

**Issue by kurmachu** [lblommesteyn/personal-site#1]
There is a strange strip on the left of the document in both Chrome and Firefox (safari untested). It is probably unintentional.
![image](https://user-images.githubusercontent.com/31492625/181996084-b967c8ca-131c-4919-a7d4-b94e88bba93f.png)
![image](https://user-images.githubusercontent.com/31492625/181996088-e9962429-b45d-4a3a-bbd9-5f2579f07ea3.png)
![image](https://user-images.githubusercontent.com/31492625/181996092-d2e08218-fbbf-44a0-a8e4-0f105cb187fc.png)

This is easily fixed by setting the body margin to 0.
```css
body {
     margin: 0;
}
```

By default body has a small margin, this is a holdover from when html was just for documents. Probably. You can ask a historian.
![image](https://user-images.githubusercontent.com/31492625/181996161-864f0e8b-e920-4558-b79e-f722ee1c1592.png)
![image](https://user-images.githubusercontent.com/31492625/181996213-9f54ecac-6fed-41a0-bad4-b16584f450d1.png)

It could also be that you do intentionally want the gradient there you just don't want it to scroll, but the implementation leads me to believe that isn't the case.

**Comment by lblommesteyn** [comment]
It’s fixed locally lol, just I haven’t pushed it to git lol

Best,
Luke Blommesteyn
